name: Notion Slack Notify

on:
  schedule:
    # 毎日9時(JST)に実行（GitHubはUTCなので0時）
    - cron: "0 0 * * *"
  workflow_dispatch:  # 手動実行も可能

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py